//------------------------------------------------ ------------------------------
// <auto-generated>
// This code was generated by a tool.
// Runtime Version: 4.0.30319.235
//
// Changes to this file may cause unexpected behavior and will be lost if
// The code is regenerated.
// </ Auto-generated>
//------------------------------------------------ ------------------------------

namespace QuestorStatistics.Properties {
    using System;


    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos para buscar cadenas traducidas, etc.
    /// </summary>
    // This class was automatically generated StronglyTypedResourceBuilder
    // Through a tool like Visual Studio or ResGen.
    // To add or remove a member, edit the file. ResX and then rerun ResGen
    // With the / str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Resource class typed to look for localized strings, etc..
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuestorStatistics.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's current ownership for all
        ///   resource lookups using this kind of resources typed.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
    }
}
